### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/tcl#160]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/tcl/issues/151)
- [x] [Add key features](https://github.com/exercism/tcl/issues/152)
- [x] [Add tags](https://github.com/exercism/tcl/issues/153)
- [ ] [Update status of Concept Exercises](https://github.com/exercism/tcl/issues/159)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/tcl/issues/154)
- [x] [Update status of track](https://github.com/exercism/tcl/issues/158)
- [x] [Pass linting checks](https://github.com/exercism/tcl/issues/155)
- [x] [Build Test Runner](https://github.com/exercism/tcl/issues/156)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/tcl/issues/157) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7

**Comment by glennj** [comment]
Update current status: [Configure online editor](https://github.com/exercism/tcl/pull/178), [Add key features](https://github.com/exercism/tcl/pull/174), [Build Test Runner](https://github.com/exercism/tcl/pull/184)

**Comment by glennj** [comment]
Concept exercises are yet to be written.

**Comment by glennj** [comment]
Closing. Concepts will be tracked with new issues.
