### ISSUE TITLE
Bootstrap Tcl track

### ISSUE THREAD

**Issue by sshine** [exercism/tcl#3]
- [x] Update docs: #4
- [x] Implement Hello World: #5
- [x] CI for checking validity of example
- [ ] Set up commit hook and policy for PR-driven development
- [ ] Find json library for extracting canonical data for exercises
- [ ] Build test generator

**Comment by sshine** [comment]
Going over [the checklist](https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md):
- [x] ~~Select programming language variant~~ (not applicable)
- [x] Select testing framework: `tcltest` ships with tclsh8.4+
- [x] Write first exercise: #5 (hello-world)
- [x] Plan initial core exercises: The plan is to first copy the Ruby core track.
- [x] Add the track to the site as inactive
- [x] Request a track icon: exercism/website-icons#26
- [ ] Plan optional exercises
- [ ] Write ["getting started" instructions](https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md#write-getting-started-instructions-for-people-using-the-track): Installation instructions not done yet; work in progress: #4.

**Comment by sshine** [comment]
https://wuhrr.wordpress.com/2011/03/28/getting-started-with-tcltest/

**Comment by sshine** [comment]
Idea by @sebres for making single-file testing fail fast:

    proc test args {
        upvar ::tcltest::numTests numTests
        set numTestsFailed $nt(Failed)
        uplevel [list ::tcltest::test {*}$args]
        if {$nt(Failed) > $numTestsFailed} {
            puts "*** EXIT ON ERROR ***"
            exit 1
        }
    }

**Comment by sebres** [comment]
well, initially I wrote:
```diff
-    upvar ::tcltest::numTests numTests
+    upvar ::tcltest::numTests nt
```
so either rename `nt` var everywhere (or apply fix above;)

**Comment by sshine** [comment]
Thanks. :-) I'll save your second suggestion here as well:

    trace add variable ::tcltest::numTests(Failed) write {apply {args {puts {*** EXIT ON ERROR ***}; exit 1}}}

**Comment by sshine** [comment]
Closing this issue, since the Tcl track has been bootstrapped without test generators so far.
